# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a05afc8c5e62fc67866bf8339ee9eb2e0c8fafad89d37e01866c1641733b16cb31e0efd43bfa6f2b334d0b0ec7c886af1ab10bf804e10269ee095033cacd1899

test:
  secret_key_base: 8dbc55d867c69f000f1ecc19c78a1d409d30d2a6edb7b10ca37e493ce529d4754b284f903d0e17cc875cdf6f42010aa19de3ca629566e3d68f82a2c235595e36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
